### ISSUE TITLE
Proposte talk 28 luglio

### ISSUE THREAD

**Issue by teone** [MeanMilan/meanmilan.github.io#1]
Quattro Lighting Talk a cura della Community, proponi il tuo! Hai tempo fino al <b>10 luglio</b> per proporre il tuo talk, <b>dal 10 al 22 luglio</b> sarà aperto un sondaggio per scegliere i quattro talk vincitori, che saranno tenuti durante il meetup di Luglio.

I talk avranno una durata di 15 minuti. Sarà messo a disposizione un proiettore, dovrai portare il tuo computer dal quale mostrare le slide.

Rispondi a questo issue per qualsiasi domanda o per proporre un talk!

**Comment by pmontrasio** [comment]
Un talk su [Asm.js](http://asmjs.org/) ed [emscripten](http://kripken.github.io/emscripten-site/).

L'esempio d'uso specifico è ancora da decidere. Per non limitarsi al banale "ma quanto è veloce asm.js!" un candidato è "Newton e asm.js", ossia come prendere un algoritmo astronomico in C del 1987 e trasformarlo in automatico in JavaScript per essere usato dentro ad una pagina web.

**Comment by pietro909** [comment]
Demistifying the 3D web
[WebGL](https://www.khronos.org/webgl/) sta rendendo possibile veicolare contenuti 3D nativamente su moltissime piattaforme diverse, e framework del calibro di [ThreeJS](http://threejs.org/) hanno semplificato concetti complessi come la gestione della scena e delle luci: il risultato è un workflow più semplice, alla portata di tutti gli sviluppatori.

**Comment by nkint** [comment]
Versione aggiornata, al posto di concentrarsi solo du ThreeJS forse è più interessante uno showcase di progetti (webgl o collaterali) per dare una panoramica un po' più ampia.

Demistifying the 3D web
WebGL sta rendendo possibile veicolare contenuti 3D su piattaforme diverse, rendendo lo sviluppo 3D più semplice e alla portata di tutti gli sviluppatori.
In questo talk, presetato da Khronos Group Milano a seguito di un corso su Three.js, verrà fatta una panoramica su progetti che intersecano WebGL (dalla digital fabbrication al multiplayer game, dall'integrazione con framework frontend a librerie collaterali).
Ogni progetto verrà descritto (molto) velocemente con 1 slide, lasciando al pubblico decidere alla fine dello showcase su quale spendere qualche parola in più (nel limite del tempo previsto).

**Comment by lambrojos** [comment]
Bè a me sembrano tutte cose interessanti! Personalmente approvo tutto

**Comment by teone** [comment]
Idem come sopra!

**Comment by moebiusmania** [comment]
AngularJS 2.0: It has begun!

Se finora hai solo sentito parlare della nuova versione di AngularJS ma non ci hai ancora messo mano perche non sapevi da che parte iniziare, questo talk fa per te! Ci saranno semplici esempi di codice ma questo talk sarà principalmente orientato su come è strutturato AngularJS 2.0 e come impostare il flusso di lavoro per questa nuova iterazione del framework

**Comment by fuzzybook** [comment]
Grunt Gulp o Nodejs

come gestire al meglio lo sviluppo di una webapp?

Da uno studio di fattibilità alcuni spunti di riflessione per uscire dai trend convenzionali.

**Comment by teone** [comment]
Ciao @fuzzybook, purtroppo abbiamo già chiuso le proposte per questi talk, speriamo comunque di vederti all'evento!
